[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/gemini/*"
  to = "/.netlify/functions/gemini"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
